### ISSUE TITLE
suggestion: punctuation - darken a little

### ISSUE THREAD

**Issue by rcrooks** [daydev/vscode-dark-remix#1]
hi @daydev I like this theme a lot. I have one suggestion, based on the fact that I create a lot of HTML pages, among other things. I like the brackets on tags to be a different color or shade than the tag name for readability. Can just be a little darker. Punctuation is the scope for this. I'd be happy to do it and submit a pull request if you like.

Best,
Robert

**Comment by daydev** [comment]
Hello, thanks for you interest. I considered angle brackets on tags, except I specifically wanted them the same color as the tags. I guess I got used to tags being all one color in different editors, different color brackets look a bit weird to me. So I won't be changing this at this time. 

If you want, you can put override styles in your `settings.json`, I added some information on this to the README, although you seem to already know how it works. As a note, you would likely need to override the following scope to re-color the brackets, otherwise the more specific rule in the theme would take precedence:

```
"scope": [     
                "punctuation.definition.tag",
                "punctuation.definition.tag.html",
                "punctuation.definition.tag.begin.html",
                "punctuation.definition.tag.end.html"
    ]
```
